services:
  - type: web
    name: vendor-security-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && pip3 install -r ../cyber-engine/requirements.txt
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: ALERT_EMAIL_USER
        sync: false
      - key: ALERT_EMAIL_PASS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
