const express = require("express");
const router = express.Router();
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const { OAuth2Client } = require("google-auth-library");
const User = require("../models/User");
const Scan = require("../models/Scan");

const googleClient = new OAuth2Client(process.env.GOOGLE_CLIENT_ID);

// 1. CLASSIC EMAIL SIGNUP
router.post("/signup", async (req, res) => {
  try {
    const { name, email, password } = req.body;

    if (!name || !email || !password) {
      return res.status(400).json({ error: "Please fill all required fields" });
    }

    const userExists = await User.findOne({ email });
    if (userExists) {
      return res
        .status(400)
        .json({ error: "An account with this email already exists" });
    }

    // Hash the password securely using bcrypt
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    const newUser = new User({
      name,
      email,
      password: hashedPassword,
    });

    await newUser.save();

    // Create user session token
    const token = jwt.sign({ id: newUser._id }, process.env.JWT_SECRET, {
      expiresIn: "1d",
    });
    return res
      .status(201)
      .json({
        token,
        user: { id: newUser._id, name: newUser.name, email: newUser.email },
      });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: "Server authentication error" });
  }
});

// 2. CLASSIC EMAIL LOGIN
router.post("/login", async (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({ error: "Missing login credentials" });
    }

    const user = await User.findOne({ email });
    if (!user || !user.password) {
      return res
        .status(400)
        .json({
          error: "Invalid credentials or account registered via Google",
        });
    }

    const isMatch = await bcrypt.compare(password, user.password);
    if (!isMatch) {
      return res.status(400).json({ error: "Invalid password credentials" });
    }

    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET, {
      expiresIn: "1d",
    });
    return res.json({
      token,
      user: { id: user._id, name: user.name, email: user.email },
    });
  } catch (err) {
    return res.status(500).json({ error: "Server authentication error" });
  }
});

// 3. GOOGLE OAUTH IDENTITY SIGN-IN
router.post("/google", async (req, res) => {
  try {
    const { credential } = req.body;

    if (!credential) {
      return res
        .status(400)
        .json({ error: "Google credentials token missing" });
    }

    // Verify that the incoming token is valid and generated by Google's Auth servers
    const ticket = await googleClient.verifyIdToken({
      idToken: credential,
      audience: process.env.GOOGLE_CLIENT_ID,
    });

    const { name, email, picture, sub: googleId } = ticket.getPayload();

    // Check if user already exists via email or Google account ID
    let user = await User.findOne({ email });

    if (!user) {
      // Create user profile on-the-fly if logging in for the first time
      user = new User({
        name,
        email,
        googleId,
        avatar: picture,
      });
      await user.save();
    } else if (!user.googleId) {
      // If user previously registered with email, link their Google account
      user.googleId = googleId;
      user.avatar = picture;
      await user.save();
    }

    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET, {
      expiresIn: "1d",
    });
    return res.json({
      token,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        avatar: user.avatar,
      },
    });
  } catch (err) {
    console.error("Google auth validation failed ❌:", err);
    return res
      .status(400)
      .json({ error: "Google verification token is invalid" });
  }
});

// 4. GET PAST SCANS FOR THE LOGGED-IN USER
router.get("/scans/:email", async (req, res) => {
  try {
    const { email } = req.params;
    const history = await Scan.find({ userEmail: email.toLowerCase() })
      .sort({ scannedAt: -1 })
      .lean();
    // Stringify _id so the frontend receives a plain string, not an ObjectId object
    const normalized = history.map((s) => ({ ...s, _id: s._id.toString() }));
    res.json({ success: true, history: normalized });
  } catch (err) {
    console.error("Failed to fetch historical ledger ❌:", err);
    res.status(500).json({ success: false, error: "Internal server registry breakdown" });
  }
});

// 5. DELETE A SCAN BY ID
router.delete("/scans/:id", async (req, res) => {
  try {
    const deleted = await Scan.findByIdAndDelete(req.params.id);
    if (!deleted) return res.status(404).json({ success: false, error: "Scan not found" });
    res.json({ success: true });
  } catch (err) {
    console.error("Failed to delete scan ❌:", err);
    res.status(500).json({ success: false, error: "Delete operation failed" });
  }
});

module.exports = router;
